object Version {
    const val customPlugins = "1.0.3"
    const val gmsPlugin = "4.0.1"
    const val gradlePlugin = "3.1.1"
    const val fabricPlugin = "1.24.4"
    const val hugoPlugin = "1.2.1"
    
    const val andutils = "1.0.35"
    const val jutils = "1.0.7"
    const val firebaseutils = "1.0.1"
    const val resutils = "1.0.3"
    const val rangebar = "1.0.3"
    const val stackoverflowtag = "1.0.5"

    const val java7 = "1.7"
    const val java8 = "1.8"
    const val kotlin = "1.2.51"
    const val kotlinCoroutine = "0.21"
    const val anko = "0.10.3"
    const val gms = "11.8.0"
    const val firebase = "11.8.0"
    const val support = "27.1.1"
    const val androidPlugin = "3.1.0"
    const val glide = "4.5.0"
    const val rxJava = "2.1.9"
    const val rxJavaAndroid = "2.0.1"
    const val mapStruct = "1.2.0.Final"
    const val constraintLayout = "1.0.2"
    const val firebaseUi = "3.2.2"
    const val mosbyMvi = "3.1.0"
    const val rxBinding = "2.1.0"
    const val dagger = "2.15"
    const val joda = "2.9.9"
    const val crystalRange = "1.1.3"
    const val imageCropper = "2.5.1"
    const val imageCompressor = "2.1.0"
    const val circleIndicator = "1.2.2@aar"
    const val circleImageView = "2.2.0"
    const val keyboardVisibility = "2.1.0"
    const val jUnit = "4.12"
    const val supportTest = "1.0.1"
    const val espresso = "3.0.1"
    const val crashLytics = "2.7.1@aar"
    const val apacheValidator = "1.6"
    const val javaxInject = "1"
    const val koin = "0.9.2"
    const val room = "1.0.0"
    const val mockito = "2.18.3"
    const val mockitoKotlin = "1.5.0"
    const val powermock = "1.6.5"
    const val androidKtx = "0.3"
    const val frodo = "0.8.3"
    const val retrofit2 = "2.4.0"
    const val retrofit2CoroutineAdapter = "1.0.0"
    const val buildTimeTracker = "0.11.0"
    const val archLifecycle = "1.1.1"
    const val okLog = "2.3.0"
    const val archNavigation = "1.0.0-alpha02"
}

object Lib {
    const val andutils = "com.jueggs:andutils:${Version.andutils}"
    const val jutils = "com.jueggs:jutils:${Version.jutils}"
    const val firebaseutils = "com.jueggs:firebaseutils:${Version.firebaseutils}"
    const val resutils = "com.jueggs:resutils:${Version.resutils}"
    const val rangebar = "com.jueggs.customview:rangebar:${Version.rangebar}"
    const val stackoverflowtag = "com.jueggs.customview:stackoverflowtag:${Version.stackoverflowtag}"
    
    const val kotlinStd7 = "org.jetbrains.kotlin:kotlin-stdlib-jdk7:${Version.kotlin}"
    const val kotlinStd8 = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Version.kotlin}"
    const val kotlinReflect = "org.jetbrains.kotlin:kotlin-reflect:${Version.kotlin}"
    const val kotlinCoroutine = "org.jetbrains.kotlinx:kotlinx-coroutines-core:${Version.kotlinCoroutine}"
    const val rxJava = "io.reactivex.rxjava2:rxjava:${Version.rxJava}"
    const val rxJavaAndroid = "io.reactivex.rxjava2:rxandroid:${Version.rxJavaAndroid}"
    const val rxBinding = "com.jakewharton.rxbinding2:rxbinding-kotlin:${Version.rxBinding}"
    const val rxBindingRecyclerView = "com.jakewharton.rxbinding2:rxbinding-recyclerview-v7-kotlin:${Version.rxBinding}"
    const val appcompat = "com.android.support:appcompat-v7:${Version.support}"
    const val design = "com.android.support:design:${Version.support}"
    const val recyclerView = "com.android.support:recyclerview-v7:${Version.support}"
    const val cardView = "com.android.support:cardview-v7:${Version.support}"
    const val supportV4 = "com.android.support:support-v4:${Version.support}"
    const val supportAnnotations = "com.android.support:support-annotations:${Version.support}"
    const val exifinterface = "com.android.support:exifinterface:${Version.support}"
    const val constraintLayout = "com.android.support.constraint:constraint-layout:${Version.constraintLayout}"
    const val gridLayout = "com.android.support:gridlayout-v7:${Version.support}"
    // must equal gradle plugin version
    const val databindingCompiler = "com.android.databinding:compiler:${Version.gradlePlugin}"
    const val firebaseCore = "com.google.firebase:firebase-core:${Version.firebase}"
    const val firebaseDatabase = "com.google.firebase:firebase-database:${Version.firebase}"
    const val firebaseAuth = "com.google.firebase:firebase-auth:${Version.firebase}"
    const val firebaseCrash = "com.google.firebase:firebase-crash:${Version.firebase}"
    const val firebaseStorage = "com.google.firebase:firebase-storage:${Version.firebase}"
    const val firebaseUi = "com.firebaseui:firebase-ui-database:${Version.firebaseUi}"
    const val gmsBase = "com.google.android.gms:play-services-base:${Version.gms}"
    const val gmsLocation = "com.google.android.gms:play-services-location:${Version.gms}"
    const val mosbyMvi = "com.hannesdorfmann.mosby3:mvi:${Version.mosbyMvi}"
    const val anko = "org.jetbrains.anko:anko:${Version.anko}"
    const val ankoDesign = "org.jetbrains.anko:anko-design:${Version.anko}"
    const val ankoCommons = "org.jetbrains.anko:anko-commons:${Version.anko}"
    const val dagger = "com.google.dagger:dagger-android:${Version.dagger}"
    const val daggerSupport = "com.google.dagger:dagger-android-support:${Version.dagger}"
    const val daggerProc = "com.google.dagger:dagger-android-processor:${Version.dagger}"
    const val daggerCompiler = "com.google.dagger:dagger-compiler:${Version.dagger}"
    const val joda = "joda-time:joda-time:${Version.joda}"
    const val glide = "com.github.bumptech.glide:glide:${Version.glide}"
    const val crystalRange = "com.crystal:crystalrangeseekbar:${Version.crystalRange}"
    const val imageCropper = "com.theartofdev.edmodo:android-image-cropper:${Version.imageCropper}"
    const val imageCompressor = "id.zelory:compressor:${Version.imageCompressor}"
    const val circleIndicator = "me.relex:circleindicator:${Version.circleIndicator}"
    const val circleImageView = "de.hdodenhof:circleimageview:${Version.circleImageView}"
    const val keyboardVisibility = "net.yslibrary.keyboardvisibilityevent:keyboardvisibilityevent:${Version.keyboardVisibility}"
    const val mapStruct = "org.mapstruct:mapstruct-jdk8:${Version.mapStruct}"
    const val mapStructProc = "org.mapstruct:mapstruct-processor:${Version.mapStruct}"
    const val crashLytics = "com.crashlytics.sdk.android:crashlytics:${Version.crashLytics}"
    const val apacheValidator = "commons-validator:commons-validator:${Version.apacheValidator}"
    const val glideCompiler = "com.github.bumptech.glide:compiler:${Version.glide}"
    const val javaxInject = "javax.inject:javax.inject:${Version.javaxInject}"
    const val koin = "org.koin:koin-android:${Version.koin}"
    const val koinAndroid = "org.koin:koin-android:${Version.koin}"
    const val koinAndroidArchitecture = "org.koin:koin-android-architecture:${Version.koin}"
    const val roomRuntime = "android.arch.persistence.room:runtime:${Version.room}"
    const val roomCompiler = "android.arch.persistence.room:compiler:${Version.room}"
    const val roomRxJava = "android.arch.persistence.room:rxjava2:${Version.room}"
    const val archLifecycleExtensions = "android.arch.lifecycle:extensions:${Version.archLifecycle}"
    const val archLifecycleCompiler = "android.arch.lifecycle:compiler:${Version.archLifecycle}"
    const val archLifecycleRuntime = "android.arch.lifecycle:runtime:${Version.archLifecycle}"
    const val archLifecycleViewModel = "android.arch.lifecycle:viewmodel:${Version.archLifecycle}"
    const val archLiveDataCore = "android.arch.lifecycle:livedata-core:${Version.archLifecycle}"
    const val androidKtx = "androidx.core:core-ktx:${Version.androidKtx}"
    const val retrofit2 = "com.squareup.retrofit2:retrofit:${Version.retrofit2}"
    const val retrofit2GsonConverter = "com.squareup.retrofit2:converter-gson:${Version.retrofit2}"
    const val retrofit2CoroutineAdapter = "com.jakewharton.retrofit:retrofit2-kotlin-coroutines-experimental-adapter:${Version.retrofit2CoroutineAdapter}"
    const val okLog = "com.github.simonpercic:oklog3:${Version.okLog}"
    const val archNavigationFragment = "android.arch.navigation:navigation-fragment-ktx:${Version.archNavigation}"
    const val archNavigationUi = "android.arch.navigation:navigation-ui-ktx:${Version.archNavigation}"
    const val archNavigationSafeArgs = "android.arch.navigation:navigation-safe-args-gradle-plugin:${Version.archNavigation}"
    // testing
    const val jUnit = "junit:junit:${Version.jUnit}"
    const val testRunner = "com.android.support.test:runner:${Version.supportTest}"
    const val testRules = "com.android.support.test:rules:${Version.supportTest}"
    const val espressoCore = "com.android.support.test.espresso:espresso-core:${Version.espresso}"
    const val espressoIntents = "com.android.support.test.espresso:espresso-intents:${Version.espresso}"
    const val mockito = "org.mockito:mockito-core:${Version.mockito}"
    const val powermock = "org.powermock:powermock:${Version.powermock}"
    const val mockitoKotlin = "com.nhaarman:mockito-kotlin:${Version.mockitoKotlin}"
}

object Plugin {
    const val custom = "com.jueggs:gradleplugins:${Version.customPlugins}"
    const val gradle = "com.android.tools.build:gradle:${Version.gradlePlugin}"
    const val kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Version.kotlin}"
    const val gms = "com.google.gms:google-services:${Version.gmsPlugin}"
    const val fabric = "io.fabric.tools:gradle:${Version.fabricPlugin}"
    const val hugo = "com.jakewharton.hugo:hugo-plugin:${Version.hugoPlugin}"
    const val frodo = "com.fernandocejas.frodo:frodo-plugin:${Version.frodo}"
    const val buildTimeTracker = "net.rdrei.android.buildtimetracker:gradle-plugin:${Version.buildTimeTracker}"
}

object PluginId {
    const val androidApplication = "com.android.application"
    const val androidLibrary = "com.android.library"
    const val javaLibrary = "java-library"
    const val kotlin = "kotlin"
    const val kotlinAndroid = "kotlin-android"
    const val kotlinKapt = "kotlin-kapt"
    const val kotlinAndroidExtensions = "kotlin-android-extensions"
    const val gms = "com.google.gms.google-services"
    const val archivaUpload = "custom-archivaupload"
    const val maven = "maven"
}

object Url {
    const val mavenLocalSnapshot = "http://localhost:8080/repository/snapshots"
    const val mavenLocalInternal = "http://localhost:8080/repository/internal"
    const val fabric = "https://maven.fabric.io/public"
    const val jitpack = "https://jitpack.io"
    const val maven = "https://maven.google.com/"
}
